### ISSUE TITLE
run as daemon, how, due could not made it

### ISSUE THREAD

**Issue by mckaygerhard** [rofl0r/microsocks#11]
i try to run with the "start-stop.daemon" of debian to start a default microsocks deamon per system..

but when run it not goes to background, event if i used the noup etc etc at bash

any further tips, or why does not work?

**Comment by mckaygerhard** [comment]
of course can solved rudimentary with "--make-pidfile" and "--background" but there's some plans to make the program background? (i already know its light and simple but well..)

**Comment by rofl0r** [comment]
there's plenty of ways to background a task:
- nohup
- screen
- tmux
- inetd
- write your own simple systemd service script
```
[Unit]
Description=My Service NAME
After=network.target

[Service]
Type=simple
User=YOUR_USERNAME
WorkingDirectory=/home/YOUR_USERNAME/
ExecStart=/path/to/binary
Restart=always #on-failure # or always, on-abort, etc

[Install]
WantedBy=multi-user.target
```

**Comment by mckaygerhard** [comment]
thanks @rofl0r but as i said, i created but the binary does not acept the parameters (custon port sources from a file)

the service name and the init daemon works as i posted in second comment, but due the nature of the executable, does not permit control, reload or parse custom parameters..

**Comment by mckaygerhard** [comment]
yeah, it works with noup, also with screen, but only if i do manually..  i mean if i put in other script and try to automatically pass arguments, seems do not work.. dont worry, too busy for simple task.. thanks in any case.

**Comment by rofl0r** [comment]
```c
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>

void daemonize(void) {
        pid_t pid = fork();
        if (pid < 0) {
                exit(1);
        }
        if (pid > 0) exit(0);
        setsid(); /* obtain a new process group */
        int fd;
        for (fd = getdtablesize(); fd >= 0; --fd) close(fd); /* close all descriptors $
        fd = open("/dev/null", O_RDWR); dup(fd); dup(fd); /* handle standart I/O */
}
```
here's the code to deamonize (from libulz), you can add it to the file and call it from main() but i think your issue is PEBKAC so i'm not gonna put this into the official version...

**Comment by mckaygerhard** [comment]
hey solved! was a stupid misctake, the parse variable for the arguments was different, i could not see due i use a remote screen so image are blurry and well.. 

i made a debian package if interesting..  for Debian 7, 8, and 8, for debian 6, 5, and 4 too bit at venenux mail list.. here-s the procedure to install:

https://software.opensuse.org//download.html?project=home%3Avegnuli%3Ainternet&package=microsocks

```
echo 'deb http://download.opensuse.org/repositories/home:/vegnuli:/internet/Debian_$(lsb_release -s -r | cut -d . -f 1).0/ /' > /etc/apt/sources.list.d/home:vegnuli:internet.list
apt-get update
apt-get install microsocks
```
