### ISSUE TITLE
Always crash on FreeBSD 9

### ISSUE THREAD

**Issue by 404neko** [rofl0r/microsocks#21]
Program always crash when doing domain resolving.
After calling resolve(const char *host, unsigned short port, struct addrinfo** addr), it crash.
Do you have any idea about it?
Thanks

**Comment by rofl0r** [comment]
could you try whether this change fixes it ? https://github.com/rofl0r/microsocks/issues/6#issuecomment-384757566

**Comment by 404neko** [comment]
> could you try whether this change fixes it ? [#6 (comment)](https://github.com/rofl0r/microsocks/issues/6#issuecomment-384757566)

It works~
Thanks~

**Comment by rofl0r** [comment]
could you try to figure out the minimum value that works ? like try e.g. 128*1024, 256*1024, etc

**Comment by timp87** [comment]
Probably fixed in https://github.com/rofl0r/microsocks/commit/20d17e3c45ae43be50687918b0ef658088d0214b
