### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by OnceUponALoop** [rofl0r/microsocks#30]
@rofl0r - will you be tagging the new changes to `poll` with a new version?

**Comment by rofl0r** [comment]
yes, but i was hoping to get some feedback on it first since i didn't test it extensively.

**Comment by Mattraks** [comment]
Will UDP support be added in the next update?

**Comment by rofl0r** [comment]
> Will UDP support be added in the next update?

no, that's not really in my TODO list. the number of applications that can only be used via UDP and support a socks server can be counted on one hand. if someone else does the work and the quality is sufficient it may at some point be added though.

**Comment by rofl0r** [comment]
https://github.com/rofl0r/microsocks/releases/tag/v1.0.2
