### ISSUE TITLE
Resolving hostname with microsocks.

### ISSUE THREAD

**Issue by hongyi-zhao** [rofl0r/microsocks#37]
I'm not sure whether `microsocks` supports the socks5h protocol, that is, the hostname is resolved remotely on the socks5 server instead of the client.

Any hints will be highly appreciated.

Regards,
HY

**Comment by srd424** [comment]
Yes, I'm using it in that mode.

**Comment by rofl0r** [comment]
https://github.com/rofl0r/microsocks/blob/c4b927bd2f9f7444f65d64f93c356b79f1c6d3e8/sockssrv.c#L129-L135

**Comment by hongyi-zhao** [comment]
I checked [the corresponding code snippet](https://github.com/rofl0r/microsocks/blob/c4b927bd2f9f7444f65d64f93c356b79f1c6d3e8/sockssrv.c#L108), and it seems that it's the default and only supported work manner to resolve hostname with `microsocks` remotely. Is my understanding correct?

Regards,
HY

**Comment by srd424** [comment]
It seems to work in both - looking at code, I guess the client tags the connect request with a type flag to say whether it's supply an IP address or a hostname.

**Comment by hongyi-zhao** [comment]
Do you mean that the working mechanism of `microsocks` is like the following?

This will trigger the DNS resolution locally:

`$ curl -4 -x socks5://microsocks-server:1080 URL`

This will cause the DNS resolution remotely, i.e., by `microsocks`:
`$ curl -4 -x socks5h://microsocks-server:1080 URL`

**Comment by rofl0r** [comment]
try it out and use wireshark to see what's happening.

**Comment by hongyi-zhao** [comment]
Thank you very much for your notes and directions. I'll try it out.
