### ISSUE TITLE
Any reason why using microsocks with proxychains would leak DNS?

### ISSUE THREAD

**Issue by uu01** [rofl0r/microsocks#41]
I'm trying to setup a local proxy where I can configure a chain of proxies on it with proxychains. Let's say I configure proxychains to use tor and then start microsocks like this:

```
proxychains ./microsocks -i 127.0.0.1 -p 1080
```

Everything works, except that it leaks DNS.

**Comment by rofl0r** [comment]
if microsocks get passed a hostname it has naturally to do a DNS lookup. it does so using getaddrinfo(). if proxychains (i'm hoping you use proxychains-ng) is properly configured, it hooks that function call and forwards it to the next proxy. the app that uses microsocks as socks5 proxy can also leak DNS if it doesn't pass the DNS name to the proxy but rather looks it up itself (firefox e.g. has a checkbox in proxy config to enable dns lookup on proxy, but it's defaulting to off).

**Comment by uu01** [comment]
That was it. I had to set the firefox DNS lookup to proxy option.
