### ISSUE TITLE
FR: whitelist IP address in parameter

### ISSUE THREAD

**Issue by mimi89999** [rofl0r/microsocks#45]
Hello,
It would be very useful to be able to pass IP addresses that should be whitelisted as arguments.

**Comment by rofl0r** [comment]
nice work. the code of microsocks is deliberately kept simple and readable so users can easily change it to suit their specific usecase.

**Comment by Jieiku** [comment]
I see got added... I am assuming use it like this:

`microsocks -1 -i 0.0.0.0 -p 1080 -w 192.168.1.40 -u user -P password`

assuming that is correct, can you specify more than one ip for the whitelist parameter?

Thank you for this software!
