### ISSUE TITLE
Can't connect to `0.0.0.0` on client

### ISSUE THREAD

**Issue by DUOLabs333** [rofl0r/microsocks#49]
I connected to the proxy via Sagernet, but I can't access `0.0.0.0:$PORT`.

**Comment by DUOLabs333** [comment]
Using `curl` on Termux works fine.

**Comment by rofl0r** [comment]
afaik 0.0.0.0 isn't a valid ip. i'm surprised this actually works using some other programs.

**Comment by DUOLabs333** [comment]
Using 127.0.0.nip.io doesn't work either.

**Comment by rofl0r** [comment]
i've been talking to some kernel specialists and apparently handling of 0.0.0.0 is OS-dependent. linux kernel defaults to *not* route it, whereas curl uses some hacks to make it work. so relying on that 0.0.0.0 does what you expect/want isn't portable.
