### ISSUE TITLE
microsocks-1.0.2-x86_64-static may contain security issues

### ISSUE THREAD

**Issue by JianleiZhang** [rofl0r/microsocks#52]
download https://github.com/rofl0r/microsocks/releases/download/v1.0.2/microsocks-1.0.2-x86_64-static.xz
xz -d microsocks-1.0.2-x86_64-static.xz
upload microsocks-1.0.2-x86_64-static to www.virustotal.com
result:
Bkav Pro                       ASP.Webshell
Sangfor Engine Zero    Suspicious.Linux.Save.a

[939f3bc4108727cc4657ff5c6b33d56d758defe09658431e349e49acb7f925f4](https://www.virustotal.com/gui/file/939f3bc4108727cc4657ff5c6b33d56d758defe09658431e349e49acb7f925f4)

**Comment by rofl0r** [comment]
well, apparently someone somewhen created a virus or whatever using musl libc and now bogus virus checkers flag stuff using it as suspicious. you're free to decompile it by hand and compare it with the source code and find there's nothing wrong with it, or just build it yourself.
