### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by VirtualSmile** [rofl0r/microsocks#6]
I'm getting the following error printed out when trying to Test/Connect. 
"Segmentation Fault"

Added TCP_NODELAY to server.c and make > make install with no errors. Tried WITHOUT TCP_NODELAY, still given "Segmentation Fault" upon Auth.

Adding Auth with "-u test -P test" causes Auth to fail first time then cause "Segmentation Fault" on the second try. Having no Auth set instantly closes the server with "Segmentation Fault" again.

Upon adding every command line possible "server_setup: Success" but not running.

Any ideas as to why this is happening?

**Comment by rofl0r** [comment]
maybe yet another issue due to stack size. what system is this ? please give detailed info like `Ubuntu 14.14 x86_64`

**Comment by rofl0r** [comment]
try this, change line 416 from
```c
size_t stacksz = MAX(8192, PTHREAD_STACK_MIN); /* 4KB for us, 4KB for libc */
```
to
```c
size_t stacksz = 512 * 1024;
```
then run make and make install again

**Comment by VirtualSmile** [comment]
That fixed the issue! It builds and runs without issues now!! Thank you (:

**Comment by rofl0r** [comment]
great! would you be so kind as to try out some other sizes to find the "sweet spot" ?
maybe try with 256, 128, and maybe 64 KB.

**Comment by VirtualSmile** [comment]
Yea sure! You just want me to change the "512" in "512 * 1024" right? And keep going until segmentation fault happens again?

**Comment by rofl0r** [comment]
yes, exactly. thanks!

**Comment by rofl0r** [comment]
> I tried between 8 and 512 (8, 16, 32, 64, 128, 256, 512) and they all worked.

that doesn't make sense. it probably means you tested the wrong binary (i.e. you were continuing to use the old one that worked, since changing the value from 8 to 512 fixed your issue originally.

> User/Pass Auth always fails the first time, no matter what stack size I use. The second time always succeeds though.

what program are you doing the testing with ?

in my test:
terminal 1:
```
$ ./sockssrv.out -u user -P pass
client[5] 127.0.0.1: connected to xx.xx.xx.xx:80
client[4] 127.0.0.1: connected to xx.xx.xx.xx:80
client[5] 127.0.0.1: connected to xx.xx.xx.xx:80
```
terminal 2:
```
~ $ curl --socks5 user:pass@localhost:1080 google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
~ $ curl --socks5 user:pass@localhost:1080 google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
~ $ curl --socks5 user:pass@localhost:1080 google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
~ $ curl --socks5 user:passX@localhost:1080 google.com
curl: (7) User was rejected by the SOCKS5 server (5 2).
```

**Comment by VirtualSmile** [comment]
I'm actually using a Windows Proxy Checker found here: https://www.proxifier.com/download/

I'm definitely removing/deleting the old binary and rebuilding it with a new make & make install. Perhaps I should just with curl on another linux box. I'll report back as soon as I can!

**Comment by VirtualSmile** [comment]
Alright after extensive testing: It seems the problem was with the proxy checker. Although this other I'm one using gives me: "Socks5 PROTOCOL ERROR", but we can just ignore that as it works nonetheless!

As for the stack size: 8 -> 512 works perfectly fine with: 
size_t stacksz = 8 * 1024;

However, when I change it back to:
size_t stacksz = MAX(8192, PTHREAD_STACK_MIN);

I get segmentation fault.

**Comment by rofl0r** [comment]
huh. could you try putting this line after the MAX stuff ?
```c
dprintf(2, "%zu\n", stacksz);
```
and tell me what it says ?

**Comment by VirtualSmile** [comment]
Sure!

With:
`size_t stacksz = MAX(8192, PTHREAD_STACK_MIN);`
It prints: 
`16384`

With:
`size_t stacksz = 8 * 1024;`
It Prints:
`8192`

If I do `size_t stacksz = 16 * 1024;`
It Prints:
`16384` and gives `Segmentation Fault`

I think the particular size of 16384 (or 16 * 1024) is causing it.

**Comment by rofl0r** [comment]
> With: size_t stacksz = MAX(8192, PTHREAD_STACK_MIN);
> It prints: 16384

interesting. so now it works with the default ?

**Comment by VirtualSmile** [comment]
No no. It fails with the default. As long as the stackz size prints/is : 16384, it will give "Segmentation Fault".

So with: `size_t stacksz = MAX(8192, PTHREAD_STACK_MIN);`
It will Print: 16384 and give Segmentation Fault

With: `size_t stacksz = 16 * 1024;`
It will print: 16384 and give Segmentation Fault as well.

So anything that sets STACKZ to 16384 will give Segmentation fault (Including the default config/line).

**Comment by rofl0r** [comment]
...
that doesn't make sense. if it crashes, then it is due to too little stack.
so if it crashes with 16K, it should crash with 8K too...

**Comment by VirtualSmile** [comment]
Hmm.. I'm not sure as to why it crashes either :/ But it only seems to crash at 16384. It doesn't crash at 8192 or 4096. I haven't tried lower though.
