### ISSUE TITLE
Any chance of a new release with -q flag added?

### ISSUE THREAD

**Issue by binhex** [rofl0r/microsocks#61]
Hi @rofl0r, I'm very interested in the new -q flag you recently committed to master, I don't really want to keep cloning master as there maybe breaking changes in there, any chance you can create a new release please?.

For ref here is the commit with the additional flag:- https://github.com/rofl0r/microsocks/commit/655c53d27df0bd69e0ecfa8309ce2940797f3362

**Comment by ozangoktan** [comment]
@rofl0r +1 to this request, this feature would be highly relevant for use of microsocks in OpenWRT.

**Comment by rofl0r** [comment]
given that no bug has been found in years, and microsocks is pretty much feature complete, i made a release despite there being almost no changes to 1.0.3. https://github.com/rofl0r/microsocks/releases/tag/v1.0.4
